# SPDX-FileCopyrightText: 2024 Red Hat, Inc
#
# SPDX-License-Identifier: GPL-2.0-or-later

repos:
  # Generic hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
          - --keep-mock

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  # Ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.2
    hooks:
      - id: ruff

  - repo: https://github.com/myint/rstcheck
    rev: v6.2.4
    hooks:
      - id: rstcheck
        additional_dependencies: [sphinx, tomli]

  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse
